-- ═══════════════════════════════════════════════════════════════
-- CleanFlow KE — HygeneX Agent Support Tables
-- Append and run in Supabase SQL Editor (after schema.sql)
-- ═══════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════
-- 5. NOTIFICATIONS TABLE
--    Queued push/sms notifications created by the agent or app.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.notifications (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  estate        TEXT,
  title         TEXT NOT NULL,
  body          TEXT NOT NULL,
  severity      TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  channel       TEXT NOT NULL DEFAULT 'push' CHECK (channel IN ('push', 'sms', 'both')),
  is_broadcast  BOOLEAN DEFAULT false,
  triggered_by  TEXT DEFAULT 'system',
  delivered     BOOLEAN DEFAULT false,
  read_at       TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see their own notifications"
  ON public.notifications FOR SELECT
  USING (auth.uid() = user_id OR is_broadcast = true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;


-- ════════════════════════════════════════════════════════════════
-- 6. REWARDS TABLE
--    CleanFlow green points ledger per user.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.rewards (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  points      INTEGER NOT NULL CHECK (points > 0),
  reason      TEXT NOT NULL,
  category    TEXT CHECK (category IN ('segregation', 'booking', 'reporting', 'streak', 'community')),
  awarded_by  TEXT DEFAULT 'system',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own rewards"
  ON public.rewards FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service inserts rewards"
  ON public.rewards FOR INSERT
  WITH CHECK (true);

-- Add cumulative reward_points column to profiles if not exists
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS reward_points INTEGER DEFAULT 0;

-- RPC function to safely increment reward points
CREATE OR REPLACE FUNCTION increment_reward_points(p_user_id UUID, p_points INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET reward_points = COALESCE(reward_points, 0) + p_points
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ════════════════════════════════════════════════════════════════
-- 7. NEMA_REPORTS TABLE
--    NEMA compliance reports generated by the agent.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.nema_reports (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_type   TEXT NOT NULL CHECK (report_type IN ('weekly', 'monthly', 'incident', 'compliance')),
  estates       TEXT[],
  report_data   JSONB NOT NULL,
  triggered_by  TEXT DEFAULT 'hygenex_agent',
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.nema_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read reports"
  ON public.nema_reports FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Service inserts reports"
  ON public.nema_reports FOR INSERT
  WITH CHECK (true);


-- ════════════════════════════════════════════════════════════════
-- 8. AGENT_ACTIONS TABLE
--    Full audit log of every action the HygeneX agent executes.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.agent_actions (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  trigger_type  TEXT NOT NULL CHECK (trigger_type IN ('iot_alert', 'user_message', 'scheduled')),
  user_id       UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  payload       JSONB,
  decision      TEXT,
  actions       JSONB,                  -- Array of {tool, input, result, success}
  tools_called  TEXT[],
  success       BOOLEAN DEFAULT true,
  duration_ms   INTEGER,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.agent_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read agent actions"
  ON public.agent_actions FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Service inserts agent actions"
  ON public.agent_actions FOR INSERT
  WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════
-- Done! Agent support tables created.
-- ═══════════════════════════════════════════════════════════════
