-- Migration: 20240502_retroactive_company_points.sql
-- Description: Retroactively awards Track Points (GFP) to Company Owners based on the completed bookings of all their fleet drivers.

UPDATE public.profiles p
SET reward_points = COALESCE(p.reward_points, 0) + sub.total_gfp
FROM (
    -- Calculate total GFP generated by all fleet drivers belonging to each company
    SELECT 
        driver.company_id, 
        SUM(COALESCE(b.actual_weight_kg, b.weight_kg, b.bags, 0) * 5) as total_gfp
    FROM public.bookings b
    JOIN public.profiles driver ON b.agent_id = driver.id
    WHERE b.status = 'completed' 
      AND b.agent_id IS NOT NULL
      AND driver.agent_account_type = 'fleet_driver'
      AND driver.company_id IS NOT NULL
    GROUP BY driver.company_id
) sub
WHERE p.id = sub.company_id;
